### ISSUE TITLE
Doesn't seems to work on latest iOS version ( 14.2 )

### ISSUE THREAD

**Issue by clementleroy** [SvenTiigi/ValidatedPropertyKit#9]
## ValidatedPropertyKit Environment

- ValidatedPropertyKit version: 0.0.4
- macOS version: 11.0.1
- Xcode version: 12.2
- Dependency manager (Carthage, CocoaPods, SPM, Manually): SPM

## What did you do?
I have 
`@Validated(.isEmail)
    var email: String? {
        didSet {
            emailError = _email.isValid
        }
    }`
in an ObservableObject
In a view I have a TextField linked to `email`

## What did you expect to happen?

I expected the emailError to contains a bool & email to contains the text that was typed.

## What happened instead?

emailError do contains a bool but it's always false because when I type, the letter disappears. 
The value is present when I call willSet but isn't anymore in the didSet.
If I remove the call to isValid it works. 

It works as expected on devices running 14.1 or lower but not on devices running 14.2

**Comment by SvenTiigi** [comment]
Hi @clementleroy,

The current implementation of `ValidatedPropertyKit` validates the value as soon as the value is written to the property annotated with `@Validated`

https://github.com/SvenTiigi/ValidatedPropertyKit/blob/014eaa4812d8522e4a6e58b4ece8f76ae3ddcd58/Sources/Validated.swift#L190

As soon as `ValidatedPropertyKit` hits a 1.0 release this behavior will be changed so that the value only gets validated as soon as it gets accessed.
Please feel free to open up a PR.

**Comment by SvenTiigi** [comment]
Hey @clementleroy,

Please check out the latest release [`0.0.5`](https://github.com/SvenTiigi/ValidatedPropertyKit/releases/tag/0.0.5) of ValidatedPropertyKit which should resolve your issue.
